name: "Deploy a CodigoFacilito"

on:
  push:
    branches: ["master"]

jobs:
  desploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
