name: "Deploy a CodigoFacilito"

on:
  push:
    branches: ["master"]

jobs:
  desploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - name: Simulando deploy
        run: |
          echo "Hacemos pull del codigo"
          echo "Correr migraciones"
          echo "Generar binario"
          echo "Publicar version"
